# Generated by Django 4.0.1 on 2022-01-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название цены')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена урока')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя преподавателя')),
                ('image', models.ImageField(upload_to='teachers/', verbose_name='Изображение преподавателя')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Имя урока')),
                ('description', models.CharField(max_length=500, null=True)),
                ('big_description', models.TextField(verbose_name='Длинное описание уроков')),
                ('image', models.ImageField(upload_to='lessons/', verbose_name='Изображение урока')),
                ('slug', models.SlugField(unique=True)),
                ('teacher', models.ManyToManyField(to='home.Teacher', verbose_name='Преподаватель')),
            ],
        ),
    ]
